### ISSUE TITLE
unable to connect to vm through SSH - pub key

### ISSUE THREAD

**Issue by rudesome** [society-for-the-blind/nixos-azure-deploy#4]
Hi, appreciate you for taking this repo further.

I have successfully created and uploaded an nixos image and got a VM booted with the image.
But when i try to connect to the VM host over ssh, i get an `Permission denied (publickey,keyboard-interactive)` message.

I have checked the public key on the VM with `az vm show` and it matches with the key it generated locally.
Tried to connect with the command `ssh -i ~/.ssh/id_rsa username@publicIP` .
I haven't changed anything in the tr2 image nix files

Am clueless what am doing wrong 🤔

**Comment by rudesome** [comment]
solved it with setting `openssh.authorizedKeys.keys = [ (builtins.readFile ~/.ssh/id_rsa.pub) ];
`  in `system.nix` and connecting with the user you have defined, seems the "azure agent" provisioned user is not available in the nixos host

**Comment by toraritte** [comment]
Glad that you could solve it, because I've used this so long ago that I wouldn't have been able to even suggest something...:) More importantly, thank you for providing the answer for future reference!
